# Generated by Django 3.1.5 on 2021-01-31 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='districts',
            field=models.ManyToManyField(to='mainapp.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.networkofcompany', verbose_name='Название сети'),
        ),
        migrations.AlterField(
            model_name='company',
            name='product',
            field=models.ManyToManyField(to='mainapp.Product', verbose_name='Имя товара'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='networkofcompany',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название Сети'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Категория'),
        ),
    ]
